/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Area,
  CreateArea,
  InvalidArea,
} from '../models/index';
import {
    AreaFromJSON,
    AreaToJSON,
    CreateAreaFromJSON,
    CreateAreaToJSON,
    InvalidAreaFromJSON,
    InvalidAreaToJSON,
} from '../models/index';

export interface CreateAreaRequest {
    body?: CreateArea;
}

export interface DeleteAreaRequest {
    id: string;
    body?: Area;
}

export interface UpdateAreaRequest {
    id: string;
    body?: Area;
}

/**
 * 
 */
export class AreaApi extends runtime.BaseAPI {

    /**
     * Create a new Area.
     */
    async createAreaRaw(requestParameters: CreateAreaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/area`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAreaToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create a new Area.
     */
    async createArea(requestParameters: CreateAreaRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createAreaRaw(requestParameters, initOverrides);
    }

    /**
     * Delete an Area or some Areas at the same time
     */
    async deleteAreaRaw(requestParameters: DeleteAreaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Area>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteArea().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/area/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: AreaToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AreaFromJSON(jsonValue));
    }

    /**
     * Delete an Area or some Areas at the same time
     */
    async deleteArea(requestParameters: DeleteAreaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Area> {
        const response = await this.deleteAreaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch All Areas
     */
    async fetchAllAreasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/area`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Fetch All Areas
     */
    async fetchAllAreas(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.fetchAllAreasRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update an Area.
     */
    async updateAreaRaw(requestParameters: UpdateAreaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Area>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateArea().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/area/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AreaToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AreaFromJSON(jsonValue));
    }

    /**
     * Update an Area.
     */
    async updateArea(requestParameters: UpdateAreaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Area> {
        const response = await this.updateAreaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
