/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  Brand,
  CreateBrand,
  Error1,
  Error2,
  Error3,
  Error4,
  InvalidBrand,
  InvalidBrand1,
  NotFound,
} from '../models/index';
import {
  BrandFromJSON,
  BrandToJSON,
  CreateBrandFromJSON,
  CreateBrandToJSON,
  Error1FromJSON,
  Error1ToJSON,
  Error2FromJSON,
  Error2ToJSON,
  Error3FromJSON,
  Error3ToJSON,
  Error4FromJSON,
  Error4ToJSON,
  InvalidBrandFromJSON,
  InvalidBrandToJSON,
  InvalidBrand1FromJSON,
  InvalidBrand1ToJSON,
  NotFoundFromJSON,
  NotFoundToJSON,
} from '../models/index';

export interface CreateBrandRequest {
  createBrand: CreateBrand;
}

export interface DeleteBrandRequest {
  id: string;
}

export interface UpdateBrandRequest {
  id: string;
  brand: Brand;
}

/**
 *
 */
export class BrandApi extends runtime.BaseAPI {
  /**
   * Endpoint for creating new brands. Expects an array of brand names in the request body.
   * Create a new Brand.
   */
  async createBrandRaw(
    requestParameters: CreateBrandRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['createBrand'] == null) {
      throw new runtime.RequiredError(
        'createBrand',
        'Required parameter "createBrand" was null or undefined when calling createBrand().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/brand`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: CreateBrandToJSON(requestParameters['createBrand']),
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   * Endpoint for creating new brands. Expects an array of brand names in the request body.
   * Create a new Brand.
   */
  async createBrand(
    requestParameters: CreateBrandRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<any> {
    const response = await this.createBrandRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }

  /**
   * Endpoint for deleting a brand.
   * Delete a Brand
   */
  async deleteBrandRaw(
    requestParameters: DeleteBrandRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling deleteBrand().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/brand/{id}`;
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id']))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Endpoint for deleting a brand.
   * Delete a Brand
   */
  async deleteBrand(
    requestParameters: DeleteBrandRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.deleteBrandRaw(requestParameters, initOverrides);
  }

  /**
   * Fetch All Brands
   */
  async fetchAllBrandsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/brand`;

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Fetch All Brands
   */
  async fetchAllBrands(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.fetchAllBrandsRaw(initOverrides);
  }

  /**
   * Update a Brand.
   */
  async updateBrandRaw(
    requestParameters: UpdateBrandRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Brand>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling updateBrand().'
      );
    }

    if (requestParameters['brand'] == null) {
      throw new runtime.RequiredError(
        'brand',
        'Required parameter "brand" was null or undefined when calling updateBrand().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    let urlPath = `/brand/{id}`;
    urlPath = urlPath.replace(
      `{${'id'}}`,
      encodeURIComponent(String(requestParameters['id']))
    );

    const response = await this.request(
      {
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: BrandToJSON(requestParameters['brand']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      BrandFromJSON(jsonValue)
    );
  }

  /**
   * Update a Brand.
   */
  async updateBrand(
    requestParameters: UpdateBrandRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Brand> {
    const response = await this.updateBrandRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
