/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FetchAllTicketsReply,
  InternalError,
  NotFound,
} from '../models/index';
import {
    FetchAllTicketsReplyFromJSON,
    FetchAllTicketsReplyToJSON,
    InternalErrorFromJSON,
    InternalErrorToJSON,
    NotFoundFromJSON,
    NotFoundToJSON,
} from '../models/index';

export interface FetchAllTicketsRequest {
    ticketNumber?: string;
    limit?: number;
    date?: Date;
}

/**
 * 
 */
export class TicketApi extends runtime.BaseAPI {

    /**
     * Fetch All existing tickets
     */
    async fetchAllTicketsRaw(requestParameters: FetchAllTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FetchAllTicketsReply>> {
        const queryParameters: any = {};

        if (requestParameters['ticketNumber'] != null) {
            queryParameters['ticketNumber'] = requestParameters['ticketNumber'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tickets`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FetchAllTicketsReplyFromJSON(jsonValue));
    }

    /**
     * Fetch All existing tickets
     */
    async fetchAllTickets(requestParameters: FetchAllTicketsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FetchAllTicketsReply> {
        const response = await this.fetchAllTicketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
