/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AreaRequestParams
 */
export interface AreaRequestParams {
    /**
     * Unique identifier for the area.
     * @type {string}
     * @memberof AreaRequestParams
     */
    id: string;
}

/**
 * Check if a given object implements the AreaRequestParams interface.
 */
export function instanceOfAreaRequestParams(value: object): value is AreaRequestParams {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AreaRequestParamsFromJSON(json: any): AreaRequestParams {
    return AreaRequestParamsFromJSONTyped(json, false);
}

export function AreaRequestParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AreaRequestParams {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function AreaRequestParamsToJSON(json: any): AreaRequestParams {
    return AreaRequestParamsToJSONTyped(json, false);
}

export function AreaRequestParamsToJSONTyped(value?: AreaRequestParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

