/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Area
 */
export interface Area {
  /**
   *
   * @type {string}
   * @memberof Area
   */
  name: string;
}

/**
 * Check if a given object implements the Area interface.
 */
export function instanceOfArea(value: object): value is Area {
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function AreaFromJSON(json: any): Area {
  return AreaFromJSONTyped(json, false);
}

export function AreaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Area {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
  };
}

export function AreaToJSON(json: any): Area {
  return AreaToJSONTyped(json, false);
}

export function AreaToJSONTyped(
  value?: Area | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
  };
}
