/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Brand
 */
export interface Brand {
  /**
   *
   * @type {string}
   * @memberof Brand
   */
  name: string;
}

/**
 * Check if a given object implements the Brand interface.
 */
export function instanceOfBrand(value: object): value is Brand {
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function BrandFromJSON(json: any): Brand {
  return BrandFromJSONTyped(json, false);
}

export function BrandFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Brand {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
  };
}

export function BrandToJSON(json: any): Brand {
  return BrandToJSONTyped(json, false);
}

export function BrandToJSONTyped(
  value?: Brand | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
  };
}
