/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface BrandRequestParams
 */
export interface BrandRequestParams {
  /**
   * Unique identifier for the brand.
   * @type {string}
   * @memberof BrandRequestParams
   */
  id: string;
}

/**
 * Check if a given object implements the BrandRequestParams interface.
 */
export function instanceOfBrandRequestParams(
  value: object
): value is BrandRequestParams {
  if (!('id' in value) || value['id'] === undefined) return false;
  return true;
}

export function BrandRequestParamsFromJSON(json: any): BrandRequestParams {
  return BrandRequestParamsFromJSONTyped(json, false);
}

export function BrandRequestParamsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): BrandRequestParams {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
  };
}

export function BrandRequestParamsToJSON(json: any): BrandRequestParams {
  return BrandRequestParamsToJSONTyped(json, false);
}

export function BrandRequestParamsToJSONTyped(
  value?: BrandRequestParams | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
  };
}
