/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateArea
 */
export interface CreateArea {
    /**
     * 
     * @type {Array<object>}
     * @memberof CreateArea
     */
    areas: Array<object>;
}

/**
 * Check if a given object implements the CreateArea interface.
 */
export function instanceOfCreateArea(value: object): value is CreateArea {
    if (!('areas' in value) || value['areas'] === undefined) return false;
    return true;
}

export function CreateAreaFromJSON(json: any): CreateArea {
    return CreateAreaFromJSONTyped(json, false);
}

export function CreateAreaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateArea {
    if (json == null) {
        return json;
    }
    return {
        
        'areas': json['areas'],
    };
}

export function CreateAreaToJSON(json: any): CreateArea {
    return CreateAreaToJSONTyped(json, false);
}

export function CreateAreaToJSONTyped(value?: CreateArea | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'areas': value['areas'],
    };
}

