/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateAreaAreasInner
 */
export interface CreateAreaAreasInner {
  /**
   * name of the new area
   * @type {string}
   * @memberof CreateAreaAreasInner
   */
  name: string;
}

/**
 * Check if a given object implements the CreateAreaAreasInner interface.
 */
export function instanceOfCreateAreaAreasInner(
  value: object
): value is CreateAreaAreasInner {
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function CreateAreaAreasInnerFromJSON(json: any): CreateAreaAreasInner {
  return CreateAreaAreasInnerFromJSONTyped(json, false);
}

export function CreateAreaAreasInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateAreaAreasInner {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
  };
}

export function CreateAreaAreasInnerToJSON(json: any): CreateAreaAreasInner {
  return CreateAreaAreasInnerToJSONTyped(json, false);
}

export function CreateAreaAreasInnerToJSONTyped(
  value?: CreateAreaAreasInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
  };
}
