/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateUserUsersInner
 */
export interface CreateUserUsersInner {
    /**
     * 
     * @type {string}
     * @memberof CreateUserUsersInner
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserUsersInner
     */
    lastName: string;
    /**
     * 
     * @type {number}
     * @memberof CreateUserUsersInner
     */
    areaId?: number;
}

/**
 * Check if a given object implements the CreateUserUsersInner interface.
 */
export function instanceOfCreateUserUsersInner(value: object): value is CreateUserUsersInner {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    return true;
}

export function CreateUserUsersInnerFromJSON(json: any): CreateUserUsersInner {
    return CreateUserUsersInnerFromJSONTyped(json, false);
}

export function CreateUserUsersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserUsersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'areaId': json['areaId'] == null ? undefined : json['areaId'],
    };
}

export function CreateUserUsersInnerToJSON(json: any): CreateUserUsersInner {
    return CreateUserUsersInnerToJSONTyped(json, false);
}

export function CreateUserUsersInnerToJSONTyped(value?: CreateUserUsersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'areaId': value['areaId'],
    };
}

