/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBrand
 */
export interface CreateBrand {
    /**
     * 
     * @type {Array<object>}
     * @memberof CreateBrand
     */
    brands: Array<object>;
}

/**
 * Check if a given object implements the CreateBrand interface.
 */
export function instanceOfCreateBrand(value: object): value is CreateBrand {
    if (!('brands' in value) || value['brands'] === undefined) return false;
    return true;
}

export function CreateBrandFromJSON(json: any): CreateBrand {
    return CreateBrandFromJSONTyped(json, false);
}

export function CreateBrandFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBrand {
    if (json == null) {
        return json;
    }
    return {
        
        'brands': json['brands'],
    };
}

export function CreateBrandToJSON(json: any): CreateBrand {
    return CreateBrandToJSONTyped(json, false);
}

export function CreateBrandToJSONTyped(value?: CreateBrand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'brands': value['brands'],
    };
}

