/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateBrandBrandsInner
 */
export interface CreateBrandBrandsInner {
  /**
   *
   * @type {string}
   * @memberof CreateBrandBrandsInner
   */
  name: string;
}

/**
 * Check if a given object implements the CreateBrandBrandsInner interface.
 */
export function instanceOfCreateBrandBrandsInner(
  value: object
): value is CreateBrandBrandsInner {
  if (!('name' in value) || value['name'] === undefined) return false;
  return true;
}

export function CreateBrandBrandsInnerFromJSON(
  json: any
): CreateBrandBrandsInner {
  return CreateBrandBrandsInnerFromJSONTyped(json, false);
}

export function CreateBrandBrandsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateBrandBrandsInner {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
  };
}

export function CreateBrandBrandsInnerToJSON(
  json: any
): CreateBrandBrandsInner {
  return CreateBrandBrandsInnerToJSONTyped(json, false);
}

export function CreateBrandBrandsInnerToJSONTyped(
  value?: CreateBrandBrandsInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value['name'],
  };
}
