/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An unknown error occurred when trying to delete a brand.
 * @export
 * @interface Error7
 */
export interface Error7 {
  /**
   *
   * @type {object}
   * @memberof Error7
   */
  error?: object;
}

/**
 * Check if a given object implements the Error7 interface.
 */
export function instanceOfError7(value: object): value is Error7 {
  return true;
}

export function Error7FromJSON(json: any): Error7 {
  return Error7FromJSONTyped(json, false);
}

export function Error7FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Error7 {
  if (json == null) {
    return json;
  }
  return {
    error: json['error'] == null ? undefined : json['error'],
  };
}

export function Error7ToJSON(json: any): Error7 {
  return Error7ToJSONTyped(json, false);
}

export function Error7ToJSONTyped(
  value?: Error7 | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    error: value['error'],
  };
}
