/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An unknown error occurred when trying to create a Brand.
 * @export
 * @interface Error4
 */
export interface Error4 {
    /**
     * 
     * @type {object}
     * @memberof Error4
     */
    error: object;
}

/**
 * Check if a given object implements the Error4 interface.
 */
export function instanceOfError4(value: object): value is Error4 {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function Error4FromJSON(json: any): Error4 {
    return Error4FromJSONTyped(json, false);
}

export function Error4FromJSONTyped(json: any, ignoreDiscriminator: boolean): Error4 {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function Error4ToJSON(json: any): Error4 {
    return Error4ToJSONTyped(json, false);
}

export function Error4ToJSONTyped(value?: Error4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

