/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotFoundError } from './NotFoundError';
import {
    NotFoundErrorFromJSON,
    NotFoundErrorFromJSONTyped,
    NotFoundErrorToJSON,
    NotFoundErrorToJSONTyped,
} from './NotFoundError';

/**
 * An unknown error occurred when trying to delete a brand.
 * @export
 * @interface Error4
 */
export interface Error4 {
    /**
     * 
     * @type {NotFoundError}
     * @memberof Error4
     */
    error?: NotFoundError;
}

/**
 * Check if a given object implements the Error4 interface.
 */
export function instanceOfError4(value: object): value is Error4 {
    return true;
}

export function Error4FromJSON(json: any): Error4 {
    return Error4FromJSONTyped(json, false);
}

export function Error4FromJSONTyped(json: any, ignoreDiscriminator: boolean): Error4 {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : NotFoundErrorFromJSON(json['error']),
    };
}

export function Error4ToJSON(json: any): Error4 {
    return Error4ToJSONTyped(json, false);
}

export function Error4ToJSONTyped(value?: Error4 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': NotFoundErrorToJSON(value['error']),
    };
}

