/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotFoundError } from './NotFoundError';
import {
  NotFoundErrorFromJSON,
  NotFoundErrorFromJSONTyped,
  NotFoundErrorToJSON,
  NotFoundErrorToJSONTyped,
} from './NotFoundError';

/**
 * An unknown error occurred when trying to create a Brand.
 * @export
 * @interface Error2
 */
export interface Error2 {
  /**
   *
   * @type {NotFoundError}
   * @memberof Error2
   */
  error: NotFoundError;
}

/**
 * Check if a given object implements the Error2 interface.
 */
export function instanceOfError2(value: object): value is Error2 {
  if (!('error' in value) || value['error'] === undefined) return false;
  return true;
}

export function Error2FromJSON(json: any): Error2 {
  return Error2FromJSONTyped(json, false);
}

export function Error2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Error2 {
  if (json == null) {
    return json;
  }
  return {
    error: NotFoundErrorFromJSON(json['error']),
  };
}

export function Error2ToJSON(json: any): Error2 {
  return Error2ToJSONTyped(json, false);
}

export function Error2ToJSONTyped(
  value?: Error2 | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    error: NotFoundErrorToJSON(value['error']),
  };
}
