/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An unknown error occurred when trying to create users.
 * @export
 * @interface Error3
 */
export interface Error3 {
    /**
     * 
     * @type {object}
     * @memberof Error3
     */
    error: object;
}

/**
 * Check if a given object implements the Error3 interface.
 */
export function instanceOfError3(value: object): value is Error3 {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function Error3FromJSON(json: any): Error3 {
    return Error3FromJSONTyped(json, false);
}

export function Error3FromJSONTyped(json: any, ignoreDiscriminator: boolean): Error3 {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function Error3ToJSON(json: any): Error3 {
    return Error3ToJSONTyped(json, false);
}

export function Error3ToJSONTyped(value?: Error3 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

