/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An unknown error occurred when trying to create a Brand.
 * @export
 * @interface Error5
 */
export interface Error5 {
  /**
   *
   * @type {object}
   * @memberof Error5
   */
  error: object;
}

/**
 * Check if a given object implements the Error5 interface.
 */
export function instanceOfError5(value: object): value is Error5 {
  if (!('error' in value) || value['error'] === undefined) return false;
  return true;
}

export function Error5FromJSON(json: any): Error5 {
  return Error5FromJSONTyped(json, false);
}

export function Error5FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Error5 {
  if (json == null) {
    return json;
  }
  return {
    error: json['error'],
  };
}

export function Error5ToJSON(json: any): Error5 {
  return Error5ToJSONTyped(json, false);
}

export function Error5ToJSONTyped(
  value?: Error5 | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    error: value['error'],
  };
}
