/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An unknown error occurred while attempting to retrieve the data.
 * @export
 * @interface Error1
 */
export interface Error1 {
    /**
     * 
     * @type {object}
     * @memberof Error1
     */
    error: object;
}

/**
 * Check if a given object implements the Error1 interface.
 */
export function instanceOfError1(value: object): value is Error1 {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function Error1FromJSON(json: any): Error1 {
    return Error1FromJSONTyped(json, false);
}

export function Error1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Error1 {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function Error1ToJSON(json: any): Error1 {
    return Error1ToJSONTyped(json, false);
}

export function Error1ToJSONTyped(value?: Error1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

