/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorSchemaJson
 */
export interface ErrorSchemaJson {
    /**
     * Code of error.
     * @type {string}
     * @memberof ErrorSchemaJson
     */
    code: string;
    /**
     * Error that has happened.
     * @type {string}
     * @memberof ErrorSchemaJson
     */
    error: string;
    /**
     * Message with information about the error.
     * @type {string}
     * @memberof ErrorSchemaJson
     */
    message: string;
}

/**
 * Check if a given object implements the ErrorSchemaJson interface.
 */
export function instanceOfErrorSchemaJson(value: object): value is ErrorSchemaJson {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ErrorSchemaJsonFromJSON(json: any): ErrorSchemaJson {
    return ErrorSchemaJsonFromJSONTyped(json, false);
}

export function ErrorSchemaJsonFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorSchemaJson {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'error': json['error'],
        'message': json['message'],
    };
}

export function ErrorSchemaJsonToJSON(json: any): ErrorSchemaJson {
    return ErrorSchemaJsonToJSONTyped(json, false);
}

export function ErrorSchemaJsonToJSONTyped(value?: ErrorSchemaJson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'message': value['message'],
    };
}

