/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An unknown error occurred when trying to delete a brand.
 * @export
 * @interface Error6
 */
export interface Error6 {
    /**
     * 
     * @type {object}
     * @memberof Error6
     */
    error?: object;
}

/**
 * Check if a given object implements the Error6 interface.
 */
export function instanceOfError6(value: object): value is Error6 {
    return true;
}

export function Error6FromJSON(json: any): Error6 {
    return Error6FromJSONTyped(json, false);
}

export function Error6FromJSONTyped(json: any, ignoreDiscriminator: boolean): Error6 {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function Error6ToJSON(json: any): Error6 {
    return Error6ToJSONTyped(json, false);
}

export function Error6ToJSONTyped(value?: Error6 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

