/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface FetchAllUsers
 */
export interface FetchAllUsers {
    /**
     * 
     * @type {Array<User>}
     * @memberof FetchAllUsers
     */
    users?: Array<User>;
}

/**
 * Check if a given object implements the FetchAllUsers interface.
 */
export function instanceOfFetchAllUsers(value: object): value is FetchAllUsers {
    return true;
}

export function FetchAllUsersFromJSON(json: any): FetchAllUsers {
    return FetchAllUsersFromJSONTyped(json, false);
}

export function FetchAllUsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchAllUsers {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(UserFromJSON)),
    };
}

export function FetchAllUsersToJSON(json: any): FetchAllUsers {
    return FetchAllUsersToJSONTyped(json, false);
}

export function FetchAllUsersToJSONTyped(value?: FetchAllUsers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(UserToJSON)),
    };
}

