/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginReplyUser } from './LoginReplyUser';
import {
    LoginReplyUserFromJSON,
    LoginReplyUserFromJSONTyped,
    LoginReplyUserToJSON,
    LoginReplyUserToJSONTyped,
} from './LoginReplyUser';

/**
 * 
 * @export
 * @interface FetchUserReply
 */
export interface FetchUserReply {
    /**
     * 
     * @type {LoginReplyUser}
     * @memberof FetchUserReply
     */
    user?: LoginReplyUser;
}

/**
 * Check if a given object implements the FetchUserReply interface.
 */
export function instanceOfFetchUserReply(value: object): value is FetchUserReply {
    return true;
}

export function FetchUserReplyFromJSON(json: any): FetchUserReply {
    return FetchUserReplyFromJSONTyped(json, false);
}

export function FetchUserReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchUserReply {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : LoginReplyUserFromJSON(json['user']),
    };
}

export function FetchUserReplyToJSON(json: any): FetchUserReply {
    return FetchUserReplyToJSONTyped(json, false);
}

export function FetchUserReplyToJSONTyped(value?: FetchUserReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': LoginReplyUserToJSON(value['user']),
    };
}

