/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateBrandBrandsInner } from './CreateBrandBrandsInner';
import {
    CreateBrandBrandsInnerFromJSON,
    CreateBrandBrandsInnerFromJSONTyped,
    CreateBrandBrandsInnerToJSON,
    CreateBrandBrandsInnerToJSONTyped,
} from './CreateBrandBrandsInner';

/**
 * 
 * @export
 * @interface FetchAllAreasReply
 */
export interface FetchAllAreasReply {
    /**
     * 
     * @type {Array<CreateBrandBrandsInner>}
     * @memberof FetchAllAreasReply
     */
    areas: Array<CreateBrandBrandsInner>;
}

/**
 * Check if a given object implements the FetchAllAreasReply interface.
 */
export function instanceOfFetchAllAreasReply(value: object): value is FetchAllAreasReply {
    if (!('areas' in value) || value['areas'] === undefined) return false;
    return true;
}

export function FetchAllAreasReplyFromJSON(json: any): FetchAllAreasReply {
    return FetchAllAreasReplyFromJSONTyped(json, false);
}

export function FetchAllAreasReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchAllAreasReply {
    if (json == null) {
        return json;
    }
    return {
        
        'areas': ((json['areas'] as Array<any>).map(CreateBrandBrandsInnerFromJSON)),
    };
}

export function FetchAllAreasReplyToJSON(json: any): FetchAllAreasReply {
    return FetchAllAreasReplyToJSONTyped(json, false);
}

export function FetchAllAreasReplyToJSONTyped(value?: FetchAllAreasReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'areas': ((value['areas'] as Array<any>).map(CreateBrandBrandsInnerToJSON)),
    };
}

