/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FetchUserParamsJson
 */
export interface FetchUserParamsJson {
  /**
   * The unique identifier for a User.
   * @type {string}
   * @memberof FetchUserParamsJson
   */
  userId: string;
}

/**
 * Check if a given object implements the FetchUserParamsJson interface.
 */
export function instanceOfFetchUserParamsJson(
  value: object
): value is FetchUserParamsJson {
  if (!('userId' in value) || value['userId'] === undefined) return false;
  return true;
}

export function FetchUserParamsJsonFromJSON(json: any): FetchUserParamsJson {
  return FetchUserParamsJsonFromJSONTyped(json, false);
}

export function FetchUserParamsJsonFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FetchUserParamsJson {
  if (json == null) {
    return json;
  }
  return {
    userId: json['userId'],
  };
}

export function FetchUserParamsJsonToJSON(json: any): FetchUserParamsJson {
  return FetchUserParamsJsonToJSONTyped(json, false);
}

export function FetchUserParamsJsonToJSONTyped(
  value?: FetchUserParamsJson | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    userId: value['userId'],
  };
}
