/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FetchAllTicketsReplyTicketsInnerAreasInner } from './FetchAllTicketsReplyTicketsInnerAreasInner';
import {
  FetchAllTicketsReplyTicketsInnerAreasInnerFromJSON,
  FetchAllTicketsReplyTicketsInnerAreasInnerFromJSONTyped,
  FetchAllTicketsReplyTicketsInnerAreasInnerToJSON,
  FetchAllTicketsReplyTicketsInnerAreasInnerToJSONTyped,
} from './FetchAllTicketsReplyTicketsInnerAreasInner';

/**
 *
 * @export
 * @interface FetchAllTicketsReplyTicketsInner
 */
export interface FetchAllTicketsReplyTicketsInner {
  /**
   *
   * @type {number}
   * @memberof FetchAllTicketsReplyTicketsInner
   */
  id: number;
  /**
   *
   * @type {number}
   * @memberof FetchAllTicketsReplyTicketsInner
   */
  cutNumber: number;
  /**
   *
   * @type {string}
   * @memberof FetchAllTicketsReplyTicketsInner
   */
  brand: string;
  /**
   *
   * @type {string}
   * @memberof FetchAllTicketsReplyTicketsInner
   */
  style: string;
  /**
   *
   * @type {Date}
   * @memberof FetchAllTicketsReplyTicketsInner
   */
  createdAt?: Date;
  /**
   *
   * @type {Array<FetchAllTicketsReplyTicketsInnerAreasInner>}
   * @memberof FetchAllTicketsReplyTicketsInner
   */
  areas?: Array<FetchAllTicketsReplyTicketsInnerAreasInner>;
}

/**
 * Check if a given object implements the FetchAllTicketsReplyTicketsInner interface.
 */
export function instanceOfFetchAllTicketsReplyTicketsInner(
  value: object
): value is FetchAllTicketsReplyTicketsInner {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('cutNumber' in value) || value['cutNumber'] === undefined) return false;
  if (!('brand' in value) || value['brand'] === undefined) return false;
  if (!('style' in value) || value['style'] === undefined) return false;
  return true;
}

export function FetchAllTicketsReplyTicketsInnerFromJSON(
  json: any
): FetchAllTicketsReplyTicketsInner {
  return FetchAllTicketsReplyTicketsInnerFromJSONTyped(json, false);
}

export function FetchAllTicketsReplyTicketsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FetchAllTicketsReplyTicketsInner {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    cutNumber: json['cutNumber'],
    brand: json['brand'],
    style: json['style'],
    createdAt:
      json['createdAt'] == null ? undefined : new Date(json['createdAt']),
    areas:
      json['areas'] == null
        ? undefined
        : (json['areas'] as Array<any>).map(
            FetchAllTicketsReplyTicketsInnerAreasInnerFromJSON
          ),
  };
}

export function FetchAllTicketsReplyTicketsInnerToJSON(
  json: any
): FetchAllTicketsReplyTicketsInner {
  return FetchAllTicketsReplyTicketsInnerToJSONTyped(json, false);
}

export function FetchAllTicketsReplyTicketsInnerToJSONTyped(
  value?: FetchAllTicketsReplyTicketsInner | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    cutNumber: value['cutNumber'],
    brand: value['brand'],
    style: value['style'],
    createdAt:
      value['createdAt'] == null
        ? value['createdAt']
        : value['createdAt'].toISOString(),
    areas:
      value['areas'] == null
        ? undefined
        : (value['areas'] as Array<any>).map(
            FetchAllTicketsReplyTicketsInnerAreasInnerToJSON
          ),
  };
}
