/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FetchAllTicketsQueryString
 */
export interface FetchAllTicketsQueryString {
    /**
     * Filter tickets by ticket number
     * @type {string}
     * @memberof FetchAllTicketsQueryString
     */
    ticketNumber?: string;
    /**
     * Maximum number of tickets to return.
     * @type {number}
     * @memberof FetchAllTicketsQueryString
     */
    limit?: number;
    /**
     * Filter tickets by date (YYYY-MM-DD) 
     * @type {Date}
     * @memberof FetchAllTicketsQueryString
     */
    date?: Date;
}

/**
 * Check if a given object implements the FetchAllTicketsQueryString interface.
 */
export function instanceOfFetchAllTicketsQueryString(value: object): value is FetchAllTicketsQueryString {
    return true;
}

export function FetchAllTicketsQueryStringFromJSON(json: any): FetchAllTicketsQueryString {
    return FetchAllTicketsQueryStringFromJSONTyped(json, false);
}

export function FetchAllTicketsQueryStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchAllTicketsQueryString {
    if (json == null) {
        return json;
    }
    return {
        
        'ticketNumber': json['ticketNumber'] == null ? undefined : json['ticketNumber'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
    };
}

export function FetchAllTicketsQueryStringToJSON(json: any): FetchAllTicketsQueryString {
    return FetchAllTicketsQueryStringToJSONTyped(json, false);
}

export function FetchAllTicketsQueryStringToJSONTyped(value?: FetchAllTicketsQueryString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ticketNumber': value['ticketNumber'],
        'limit': value['limit'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString().substring(0,10),
    };
}

