/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FetchUserReplyUser
 */
export interface FetchUserReplyUser {
    /**
     * 
     * @type {number}
     * @memberof FetchUserReplyUser
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof FetchUserReplyUser
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof FetchUserReplyUser
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof FetchUserReplyUser
     */
    email: string;
}

/**
 * Check if a given object implements the FetchUserReplyUser interface.
 */
export function instanceOfFetchUserReplyUser(value: object): value is FetchUserReplyUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function FetchUserReplyUserFromJSON(json: any): FetchUserReplyUser {
    return FetchUserReplyUserFromJSONTyped(json, false);
}

export function FetchUserReplyUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchUserReplyUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'email': json['email'],
    };
}

export function FetchUserReplyUserToJSON(json: any): FetchUserReplyUser {
    return FetchUserReplyUserToJSONTyped(json, false);
}

export function FetchUserReplyUserToJSONTyped(value?: FetchUserReplyUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'email': value['email'],
    };
}

