/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FetchAllTicketsReplyTicketsInner } from './FetchAllTicketsReplyTicketsInner';
import {
    FetchAllTicketsReplyTicketsInnerFromJSON,
    FetchAllTicketsReplyTicketsInnerFromJSONTyped,
    FetchAllTicketsReplyTicketsInnerToJSON,
    FetchAllTicketsReplyTicketsInnerToJSONTyped,
} from './FetchAllTicketsReplyTicketsInner';

/**
 * 
 * @export
 * @interface FetchAllTicketsReply
 */
export interface FetchAllTicketsReply {
    /**
     * 
     * @type {Array<FetchAllTicketsReplyTicketsInner>}
     * @memberof FetchAllTicketsReply
     */
    tickets: Array<FetchAllTicketsReplyTicketsInner>;
}

/**
 * Check if a given object implements the FetchAllTicketsReply interface.
 */
export function instanceOfFetchAllTicketsReply(value: object): value is FetchAllTicketsReply {
    if (!('tickets' in value) || value['tickets'] === undefined) return false;
    return true;
}

export function FetchAllTicketsReplyFromJSON(json: any): FetchAllTicketsReply {
    return FetchAllTicketsReplyFromJSONTyped(json, false);
}

export function FetchAllTicketsReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchAllTicketsReply {
    if (json == null) {
        return json;
    }
    return {
        
        'tickets': ((json['tickets'] as Array<any>).map(FetchAllTicketsReplyTicketsInnerFromJSON)),
    };
}

export function FetchAllTicketsReplyToJSON(json: any): FetchAllTicketsReply {
    return FetchAllTicketsReplyToJSONTyped(json, false);
}

export function FetchAllTicketsReplyToJSONTyped(value?: FetchAllTicketsReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tickets': ((value['tickets'] as Array<any>).map(FetchAllTicketsReplyTicketsInnerToJSON)),
    };
}

