/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FetchAllTicketsReplyTicketsInnerAreasInner
 */
export interface FetchAllTicketsReplyTicketsInnerAreasInner {
    /**
     * 
     * @type {number}
     * @memberof FetchAllTicketsReplyTicketsInnerAreasInner
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof FetchAllTicketsReplyTicketsInnerAreasInner
     */
    name: string;
}

/**
 * Check if a given object implements the FetchAllTicketsReplyTicketsInnerAreasInner interface.
 */
export function instanceOfFetchAllTicketsReplyTicketsInnerAreasInner(value: object): value is FetchAllTicketsReplyTicketsInnerAreasInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function FetchAllTicketsReplyTicketsInnerAreasInnerFromJSON(json: any): FetchAllTicketsReplyTicketsInnerAreasInner {
    return FetchAllTicketsReplyTicketsInnerAreasInnerFromJSONTyped(json, false);
}

export function FetchAllTicketsReplyTicketsInnerAreasInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchAllTicketsReplyTicketsInnerAreasInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function FetchAllTicketsReplyTicketsInnerAreasInnerToJSON(json: any): FetchAllTicketsReplyTicketsInnerAreasInner {
    return FetchAllTicketsReplyTicketsInnerAreasInnerToJSONTyped(json, false);
}

export function FetchAllTicketsReplyTicketsInnerAreasInnerToJSONTyped(value?: FetchAllTicketsReplyTicketsInnerAreasInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

