/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InternalErrorError } from './InternalErrorError';
import {
  InternalErrorErrorFromJSON,
  InternalErrorErrorFromJSONTyped,
  InternalErrorErrorToJSON,
  InternalErrorErrorToJSONTyped,
} from './InternalErrorError';

/**
 * An unknown error occurred while attempting to retrieve the data.
 * @export
 * @interface InternalError
 */
export interface InternalError {
  /**
   *
   * @type {InternalErrorError}
   * @memberof InternalError
   */
  error: InternalErrorError;
}

/**
 * Check if a given object implements the InternalError interface.
 */
export function instanceOfInternalError(value: object): value is InternalError {
  if (!('error' in value) || value['error'] === undefined) return false;
  return true;
}

export function InternalErrorFromJSON(json: any): InternalError {
  return InternalErrorFromJSONTyped(json, false);
}

export function InternalErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InternalError {
  if (json == null) {
    return json;
  }
  return {
    error: InternalErrorErrorFromJSON(json['error']),
  };
}

export function InternalErrorToJSON(json: any): InternalError {
  return InternalErrorToJSONTyped(json, false);
}

export function InternalErrorToJSONTyped(
  value?: InternalError | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    error: InternalErrorErrorToJSON(value['error']),
  };
}
