/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface InternalErrorError
 */
export interface InternalErrorError {
  /**
   * Code of error.
   * @type {string}
   * @memberof InternalErrorError
   */
  code: string;
  /**
   * Error that has happened.
   * @type {string}
   * @memberof InternalErrorError
   */
  error?: string;
  /**
   * Message with information about the error.
   * @type {string}
   * @memberof InternalErrorError
   */
  message: string;
}

/**
 * Check if a given object implements the InternalErrorError interface.
 */
export function instanceOfInternalErrorError(
  value: object
): value is InternalErrorError {
  if (!('code' in value) || value['code'] === undefined) return false;
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function InternalErrorErrorFromJSON(json: any): InternalErrorError {
  return InternalErrorErrorFromJSONTyped(json, false);
}

export function InternalErrorErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InternalErrorError {
  if (json == null) {
    return json;
  }
  return {
    code: json['code'],
    error: json['error'] == null ? undefined : json['error'],
    message: json['message'],
  };
}

export function InternalErrorErrorToJSON(json: any): InternalErrorError {
  return InternalErrorErrorToJSONTyped(json, false);
}

export function InternalErrorErrorToJSONTyped(
  value?: InternalErrorError | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value['code'],
    error: value['error'],
    message: value['message'],
  };
}
