/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotFoundError } from './NotFoundError';
import {
    NotFoundErrorFromJSON,
    NotFoundErrorFromJSONTyped,
    NotFoundErrorToJSON,
    NotFoundErrorToJSONTyped,
} from './NotFoundError';

/**
 * An unknown error occurred.
 * @export
 * @interface InternalServerError
 */
export interface InternalServerError {
    /**
     * 
     * @type {NotFoundError}
     * @memberof InternalServerError
     */
    error: NotFoundError;
}

/**
 * Check if a given object implements the InternalServerError interface.
 */
export function instanceOfInternalServerError(value: object): value is InternalServerError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function InternalServerErrorFromJSON(json: any): InternalServerError {
    return InternalServerErrorFromJSONTyped(json, false);
}

export function InternalServerErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalServerError {
    if (json == null) {
        return json;
    }
    return {
        
        'error': NotFoundErrorFromJSON(json['error']),
    };
}

export function InternalServerErrorToJSON(json: any): InternalServerError {
    return InternalServerErrorToJSONTyped(json, false);
}

export function InternalServerErrorToJSONTyped(value?: InternalServerError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': NotFoundErrorToJSON(value['error']),
    };
}

