/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Invalid or missing Area data.
 * @export
 * @interface InvalidArea
 */
export interface InvalidArea {
    /**
     * 
     * @type {object}
     * @memberof InvalidArea
     */
    error: object;
}

/**
 * Check if a given object implements the InvalidArea interface.
 */
export function instanceOfInvalidArea(value: object): value is InvalidArea {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function InvalidAreaFromJSON(json: any): InvalidArea {
    return InvalidAreaFromJSONTyped(json, false);
}

export function InvalidAreaFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvalidArea {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function InvalidAreaToJSON(json: any): InvalidArea {
    return InvalidAreaToJSONTyped(json, false);
}

export function InvalidAreaToJSONTyped(value?: InvalidArea | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

