/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Invalid or missing Brand data.
 * @export
 * @interface InvalidBrand
 */
export interface InvalidBrand {
    /**
     * 
     * @type {object}
     * @memberof InvalidBrand
     */
    error: object;
}

/**
 * Check if a given object implements the InvalidBrand interface.
 */
export function instanceOfInvalidBrand(value: object): value is InvalidBrand {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function InvalidBrandFromJSON(json: any): InvalidBrand {
    return InvalidBrandFromJSONTyped(json, false);
}

export function InvalidBrandFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvalidBrand {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function InvalidBrandToJSON(json: any): InvalidBrand {
    return InvalidBrandToJSONTyped(json, false);
}

export function InvalidBrandToJSONTyped(value?: InvalidBrand | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

