/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Invalid or missing User data.
 * @export
 * @interface InvalidUser
 */
export interface InvalidUser {
  /**
   *
   * @type {object}
   * @memberof InvalidUser
   */
  error: object;
}

/**
 * Check if a given object implements the InvalidUser interface.
 */
export function instanceOfInvalidUser(value: object): value is InvalidUser {
  if (!('error' in value) || value['error'] === undefined) return false;
  return true;
}

export function InvalidUserFromJSON(json: any): InvalidUser {
  return InvalidUserFromJSONTyped(json, false);
}

export function InvalidUserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InvalidUser {
  if (json == null) {
    return json;
  }
  return {
    error: json['error'],
  };
}

export function InvalidUserToJSON(json: any): InvalidUser {
  return InvalidUserToJSONTyped(json, false);
}

export function InvalidUserToJSONTyped(
  value?: InvalidUser | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    error: value['error'],
  };
}
