/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Invalid or missing Brand.
 * @export
 * @interface InvalidBrand1
 */
export interface InvalidBrand1 {
    /**
     * 
     * @type {object}
     * @memberof InvalidBrand1
     */
    error?: object;
}

/**
 * Check if a given object implements the InvalidBrand1 interface.
 */
export function instanceOfInvalidBrand1(value: object): value is InvalidBrand1 {
    return true;
}

export function InvalidBrand1FromJSON(json: any): InvalidBrand1 {
    return InvalidBrand1FromJSONTyped(json, false);
}

export function InvalidBrand1FromJSONTyped(json: any, ignoreDiscriminator: boolean): InvalidBrand1 {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function InvalidBrand1ToJSON(json: any): InvalidBrand1 {
    return InvalidBrand1ToJSONTyped(json, false);
}

export function InvalidBrand1ToJSONTyped(value?: InvalidBrand1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

