/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Invalid or missing User.
 * @export
 * @interface InvalidUser1
 */
export interface InvalidUser1 {
  /**
   *
   * @type {object}
   * @memberof InvalidUser1
   */
  error?: object;
}

/**
 * Check if a given object implements the InvalidUser1 interface.
 */
export function instanceOfInvalidUser1(value: object): value is InvalidUser1 {
  return true;
}

export function InvalidUser1FromJSON(json: any): InvalidUser1 {
  return InvalidUser1FromJSONTyped(json, false);
}

export function InvalidUser1FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InvalidUser1 {
  if (json == null) {
    return json;
  }
  return {
    error: json['error'] == null ? undefined : json['error'],
  };
}

export function InvalidUser1ToJSON(json: any): InvalidUser1 {
  return InvalidUser1ToJSONTyped(json, false);
}

export function InvalidUser1ToJSONTyped(
  value?: InvalidUser1 | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    error: value['error'],
  };
}
