/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginReplyUser } from './LoginReplyUser';
import {
    LoginReplyUserFromJSON,
    LoginReplyUserFromJSONTyped,
    LoginReplyUserToJSON,
    LoginReplyUserToJSONTyped,
} from './LoginReplyUser';

/**
 * 
 * @export
 * @interface LoginReply
 */
export interface LoginReply {
    /**
     * 
     * @type {boolean}
     * @memberof LoginReply
     */
    success: boolean;
    /**
     * 
     * @type {LoginReplyUser}
     * @memberof LoginReply
     */
    user?: LoginReplyUser;
}

/**
 * Check if a given object implements the LoginReply interface.
 */
export function instanceOfLoginReply(value: object): value is LoginReply {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function LoginReplyFromJSON(json: any): LoginReply {
    return LoginReplyFromJSONTyped(json, false);
}

export function LoginReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginReply {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'user': json['user'] == null ? undefined : LoginReplyUserFromJSON(json['user']),
    };
}

export function LoginReplyToJSON(json: any): LoginReply {
    return LoginReplyToJSONTyped(json, false);
}

export function LoginReplyToJSONTyped(value?: LoginReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'user': LoginReplyUserToJSON(value['user']),
    };
}

