/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LoginReplyUser
 */
export interface LoginReplyUser {
  /**
   *
   * @type {number}
   * @memberof LoginReplyUser
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof LoginReplyUser
   */
  firstName: string;
  /**
   *
   * @type {string}
   * @memberof LoginReplyUser
   */
  lastName: string;
  /**
   *
   * @type {string}
   * @memberof LoginReplyUser
   */
  email: string;
}

/**
 * Check if a given object implements the LoginReplyUser interface.
 */
export function instanceOfLoginReplyUser(
  value: object
): value is LoginReplyUser {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('firstName' in value) || value['firstName'] === undefined) return false;
  if (!('lastName' in value) || value['lastName'] === undefined) return false;
  if (!('email' in value) || value['email'] === undefined) return false;
  return true;
}

export function LoginReplyUserFromJSON(json: any): LoginReplyUser {
  return LoginReplyUserFromJSONTyped(json, false);
}

export function LoginReplyUserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LoginReplyUser {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    firstName: json['firstName'],
    lastName: json['lastName'],
    email: json['email'],
  };
}

export function LoginReplyUserToJSON(json: any): LoginReplyUser {
  return LoginReplyUserToJSONTyped(json, false);
}

export function LoginReplyUserToJSONTyped(
  value?: LoginReplyUser | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    firstName: value['firstName'],
    lastName: value['lastName'],
    email: value['email'],
  };
}
