/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotFoundError } from './NotFoundError';
import {
  NotFoundErrorFromJSON,
  NotFoundErrorFromJSONTyped,
  NotFoundErrorToJSON,
  NotFoundErrorToJSONTyped,
} from './NotFoundError';

/**
 * An unknown error occurred when trying to delete areas.
 * @export
 * @interface ModelError
 */
export interface ModelError {
  /**
   *
   * @type {NotFoundError}
   * @memberof ModelError
   */
  error: NotFoundError;
}

/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): value is ModelError {
  if (!('error' in value) || value['error'] === undefined) return false;
  return true;
}

export function ModelErrorFromJSON(json: any): ModelError {
  return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ModelError {
  if (json == null) {
    return json;
  }
  return {
    error: NotFoundErrorFromJSON(json['error']),
  };
}

export function ModelErrorToJSON(json: any): ModelError {
  return ModelErrorToJSONTyped(json, false);
}

export function ModelErrorToJSONTyped(
  value?: ModelError | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    error: NotFoundErrorToJSON(value['error']),
  };
}
