/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface NotFoundError
 */
export interface NotFoundError {
  /**
   * Code of error.
   * @type {string}
   * @memberof NotFoundError
   */
  code: string;
  /**
   * Error that has happened.
   * @type {string}
   * @memberof NotFoundError
   */
  error: string;
  /**
   * Message with information about the error.
   * @type {string}
   * @memberof NotFoundError
   */
  message: string;
}

/**
 * Check if a given object implements the NotFoundError interface.
 */
export function instanceOfNotFoundError(value: object): value is NotFoundError {
  if (!('code' in value) || value['code'] === undefined) return false;
  if (!('error' in value) || value['error'] === undefined) return false;
  if (!('message' in value) || value['message'] === undefined) return false;
  return true;
}

export function NotFoundErrorFromJSON(json: any): NotFoundError {
  return NotFoundErrorFromJSONTyped(json, false);
}

export function NotFoundErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): NotFoundError {
  if (json == null) {
    return json;
  }
  return {
    code: json['code'],
    error: json['error'],
    message: json['message'],
  };
}

export function NotFoundErrorToJSON(json: any): NotFoundError {
  return NotFoundErrorToJSONTyped(json, false);
}

export function NotFoundErrorToJSONTyped(
  value?: NotFoundError | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value['code'],
    error: value['error'],
    message: value['message'],
  };
}
