/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Invalid or missing data.
 * @export
 * @interface NotFound
 */
export interface NotFound {
    /**
     * 
     * @type {object}
     * @memberof NotFound
     */
    error: object;
}

/**
 * Check if a given object implements the NotFound interface.
 */
export function instanceOfNotFound(value: object): value is NotFound {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function NotFoundFromJSON(json: any): NotFound {
    return NotFoundFromJSONTyped(json, false);
}

export function NotFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotFound {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function NotFoundToJSON(json: any): NotFound {
    return NotFoundToJSONTyped(json, false);
}

export function NotFoundToJSONTyped(value?: NotFound | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

