/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TicketJson
 */
export interface TicketJson {
    /**
     * 
     * @type {number}
     * @memberof TicketJson
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof TicketJson
     */
    cutNumber: number;
    /**
     * 
     * @type {string}
     * @memberof TicketJson
     */
    brand: string;
    /**
     * 
     * @type {string}
     * @memberof TicketJson
     */
    style: string;
}

/**
 * Check if a given object implements the TicketJson interface.
 */
export function instanceOfTicketJson(value: object): value is TicketJson {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('cutNumber' in value) || value['cutNumber'] === undefined) return false;
    if (!('brand' in value) || value['brand'] === undefined) return false;
    if (!('style' in value) || value['style'] === undefined) return false;
    return true;
}

export function TicketJsonFromJSON(json: any): TicketJson {
    return TicketJsonFromJSONTyped(json, false);
}

export function TicketJsonFromJSONTyped(json: any, ignoreDiscriminator: boolean): TicketJson {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'cutNumber': json['cutNumber'],
        'brand': json['brand'],
        'style': json['style'],
    };
}

export function TicketJsonToJSON(json: any): TicketJson {
    return TicketJsonToJSONTyped(json, false);
}

export function TicketJsonToJSONTyped(value?: TicketJson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'cutNumber': value['cutNumber'],
        'brand': value['brand'],
        'style': value['style'],
    };
}

