/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRequestParams
 */
export interface UserRequestParams {
    /**
     * Unique identifier for the user.
     * @type {string}
     * @memberof UserRequestParams
     */
    id: string;
}

/**
 * Check if a given object implements the UserRequestParams interface.
 */
export function instanceOfUserRequestParams(value: object): value is UserRequestParams {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UserRequestParamsFromJSON(json: any): UserRequestParams {
    return UserRequestParamsFromJSONTyped(json, false);
}

export function UserRequestParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRequestParams {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function UserRequestParamsToJSON(json: any): UserRequestParams {
    return UserRequestParamsToJSONTyped(json, false);
}

export function UserRequestParamsToJSONTyped(value?: UserRequestParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

