/* tslint:disable */
/* eslint-disable */
/**
 * Ticket API Swagger
 * TICKETS - Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   * Name of the user
   * @type {string}
   * @memberof User
   */
  firstName: string;
  /**
   * Last Name of the user
   * @type {string}
   * @memberof User
   */
  lastName: string;
  /**
   * ID of the area
   * @type {number}
   * @memberof User
   */
  areaId?: number;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
  if (!('firstName' in value) || value['firstName'] === undefined) return false;
  if (!('lastName' in value) || value['lastName'] === undefined) return false;
  return true;
}

export function UserFromJSON(json: any): User {
  return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): User {
  if (json == null) {
    return json;
  }
  return {
    firstName: json['firstName'],
    lastName: json['lastName'],
    areaId: json['areaId'] == null ? undefined : json['areaId'],
  };
}

export function UserToJSON(json: any): User {
  return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(
  value?: User | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    firstName: value['firstName'],
    lastName: value['lastName'],
    areaId: value['areaId'],
  };
}
